# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0NyjA5mqNw0QGjowExibIZALX5oIYAK
"""

# Install essential libraries for RAG
!pip install -q sentence-transformers faiss-cpu PyPDF2 requests

import numpy as np
import faiss
from sentence_transformers import SentenceTransformer

# 1. Define the internal document content (Requirement: Chunking)
def get_internal_docs():
    return [
        "Safety Protocol: All workers must wear Level 2 PPE, including hard hats and steel-toed boots. No-go zones are enforced near power lines. [Source: Safety Specs]",
        "Delay Policy: Construction delays are classified as Excusable (weather) or Non-Excusable (equipment failure). Revised timelines are due in 48 hours. [Source: FAQ]",
        "Inspection Specs: Site managers must perform weekly walk-throughs. During rain, inspect excavation shoring and electrical lead insulation. [Source: Maintenance Guide]",
        "Refund Policy: Contractors may request refunds for marketplace transaction fees only if the project is cancelled within 24 hours of booking. [Source: Policy Doc]",
        "Equipment Standards: Heavy machinery requires daily pre-operation checks. Failure to maintain logs results in immediate site suspension. [Source: Safety Specs]"
    ]

doc_chunks = get_internal_docs()
print(f"Loaded {len(doc_chunks)} document chunks.")

# 2. Embedding Model (Requirement: sentence-transformers)
embed_model = SentenceTransformer('all-MiniLM-L6-v2')

# 3. Vector Indexing (Requirement: FAISS)
embeddings = embed_model.encode(doc_chunks)
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings).astype('float32'))

print("Vector store is ready.")

import requests

def construction_ai_assistant(query, api_key):
    # 1. Retrieval (Semantic Search)
    query_vector = embed_model.encode([query])
    distances, indices = index.search(np.array(query_vector).astype('float32'), k=2)

    retrieved_context = [doc_chunks[i] for i in indices[0]]
    context_string = "\n".join(retrieved_context)

    # 2. Generation with Grounding Instructions
    prompt = f"""
    Answer the question STRICTLY using the context below.
    If not in context, say: "I do not have information on this in the internal documents."

    Context:
    {context_string}

    Question: {query}
    """

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": "meta-llama/llama-3-8b-instruct:free",
        "messages": [{"role": "user", "content": prompt}]
    }

    # 3. Request and Error Handling
    response = requests.post("https://openrouter.ai/api/v1/chat/completions", headers=headers, json=payload)
    res_json = response.json()

    # Check for API Errors (Key issues, model limits, etc.)
    if 'error' in res_json:
        return f"OPENROUTER ERROR: {res_json['error'].get('message', 'Unknown error')}", retrieved_context

    # Check for success
    if 'choices' in res_json:
        answer = res_json['choices'][0]['message']['content']
        return answer, retrieved_context
    else:
        return f"Unexpected API Response: {res_json}", retrieved_context

# PASTE YOUR ACTUAL KEY FROM OPENROUTER HERE
MY_OPENROUTER_KEY = "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"

# Query from the assignment instructions
question = "What factors affect construction project delays?"

answer, context = construction_ai_assistant(question, MY_OPENROUTER_KEY)

print("=== RETRIEVED CONTEXT (Explainability) ===")
for i, chunk in enumerate(context):
    print(f"Chunk {i+1}: {chunk}")

print("\n=== FINAL GENERATED ANSWER ===")
print(answer)